DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS post;


CREATE TABLE USER
(
    id       INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT        NOT NULL,
    credit INTEGER DEFAULT  100
);


CREATE TABLE post
(
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER   NOT NULL,
    created   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title     TEXT      NOT NULL,
    BODY      TEXT      NOT NULL,
    FOREIGN KEY (author_id) REFERENCES USER (id)
);
